export const SET_ANIMATION_STATE = 'SET_ANIMATION_STATE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_SIGN_STATE = 'SET_SIGN_STATE';

export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY';

export const SET_TUTORIAL_STATE = 'SET_TUTORIAL_STATE';

export const SET_SCOUTING_STATE = 'SET_SCOUTING_STATE';
