export const SET_ANIMATION_STATE = 'SET_ANIMATION_STATE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_SIGN_STATE = 'SET_SIGN_STATE';

export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY';

export const SET_TUTORIAL_STATE = 'SET_TUTORIAL_STATE';

export const UPDATE_SCOUT_PLAYER = 'UPDATE_SCOUT_PLAYER';

export const SET_STUDENT = 'SET_STUDENT';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';

export const SET_SAVINGS = 'SET_SAVINGS';

export const SCOUTING_COMPLETE = 'SCOUTING_COMPLETE';

export const SIGN_PLAYER = 'SIGN_PLAYER';

export const RELEASE_PLAYER = 'RELEASE_PLAYER';

export const TRADE_PLAYER = 'TRADE_PLAYER';

export const SET_INITIAL_PLAYERS_STATE = 'SET_INITIAL_PLAYER_STATE';

export const SET_SCORE = 'SET_SCORE';

export const SET_RANK = 'SET_RANK';

export const SET_IMAGE = 'SET_IMAGE';

export const SET_NAME = 'SET_NAME';

export const SET_STATS = 'SET_STATS';

export const SET_STANDINGS = 'SET_STANDINGS';

export const SET_NEXT_OPPONENT = 'SET_NEXT_OPPONENT';

export const SET_UPCOMING_GAMES = 'SET_UPCOMING_GAMES';

export const SET_JUMBOTRON_DISPLAY = 'SET_JUMBOTRON_DISPLAY';

export const SET_SEASON_SIGN = 'SET_SEASON_SIGN';

export const SET_SIMULATION_BUTTON = 'SET_SIMULATION_BUTTON';
