export const SET_ANIMATION_STATE = 'SET_ANIMATION_STATE';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const SET_SIGN_STATE = 'SET_SIGN_STATE';

export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY';

export const SET_TUTORIAL_STATE = 'SET_TUTORIAL_STATE';

export const UPDATE_SCOUT_PLAYER = 'UPDATE_SCOUT_PLAYER';

export const SET_STUDENT = 'SET_STUDENT';

export const UPDATE_STUDENT = 'UPDATE_STUDENT';

export const SET_SAVINGS = 'SET_SAVINGS';

export const SCOUTING_COMPLETE = 'SCOUTING_COMPLETE';

export const SIGN_PLAYER = 'SIGN_PLAYER';

export const RELEASE_PLAYER = 'RELEASE_PLAYER';

export const TRADE_PLAYER = 'TRADE_PLAYER';

export const SET_INITIAL_PLAYERS_STATE = 'SET_INITIAL_PLAYER_STATE';
